Repository DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO, pull requests merged in 2024-11, with the labels that each got.

#22 [chore] Auth 패키지 의존성 추가
  Domado/Auth/Package.swift
Labels: 🧹chore

#23 [feat] 화면 전환 제어 및 앱 상태관리 구조 설계
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/AppState/AppState.swift
  Domado/Domado/ContentView.swift
  Domado/Domado/DomadoApp.swift
  Domado/Domado/Router/AppRouter.swift
  Domado/Domado/Router/NavigationType/FullScreenDestination.swift
  Domado/Domado/Router/NavigationType/NavigationDestination.swift
  Domado/Domado/Router/NavigationType/SheetDestination.swift
  Domado/Domado/View/RootView.swift
  Domado/Domado/View/TempView/HomeView.swift
  Domado/Domado/View/TempView/InUseBikeView.swift
  Domado/Domado/View/TempView/LoadingView.swift
  Domado/Domado/View/TempView/LoginView.swift
  Domado/Domado/View/TempView/OnboardingView.swift
  Domado/Domado/View/TempView/QRScannerView.swift
  Domado/Domado/View/TempView/ReturnBikeView.swift
  Domado/Domado/View/TempView/StationDetailView.swift
  Domado/Domado/View/TempView/TempLockView.swift
Labels: 🐣feature

#25 [feat] AppError 기본 구현체 제공
  Domado/Core/Sources/Core/Error/BaseAppError.swift
Labels: 🐣feature

#27 [feat] 앱단위 에러 핸들링 시스템 구현
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/Error/AppGlobalErrorHandler.swift
  Domado/Domado/Error/ErrorAlertModifier.swift
  Domado/Domado/Error/GlobalErrorState.swift
  Domado/Domado/View/RootView.swift
Labels: 🐣feature

#29 [feat] DI Container 구현 및 의존성 주입
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/Dependency/AppContainer.swift
  Domado/Domado/DomadoApp.swift
  Domado/Domado/View/RootView.swift
Labels: 🐣feature

#31 [chore] Xcode 업데이트에 따른 프로젝트 변경
  Domado/Domado.xcodeproj/project.pbxproj
Labels: 🧹chore

#36 [chore] LocationServiceModule 세팅
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Location/.gitignore
  Domado/Location/Package.swift
  Domado/Location/Sources/Location/Data/LocationDataSource.swift
  Domado/Location/Sources/Location/Data/LocationRepository.swift
  Domado/Location/Sources/Location/Domain/LocationEntity.swift
  Domado/Location/Sources/Location/Domain/LocationUseCase.swift
  Domado/Location/Sources/Location/Location.swift
  Domado/Location/Sources/Location/Presentation/LocationView.swift
  Domado/Location/Sources/Location/Presentation/LocationViewModel.swift
  Domado/Location/Tests/LocationTests/LocationTests.swift
Labels: 🧹chore

#37 [chore] RentModule 세팅
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Rent/.gitignore
  Domado/Rent/Package.swift
  Domado/Rent/Sources/Rent/Data/RentDataSource.swift
  Domado/Rent/Sources/Rent/Data/RentRepository.swift
  Domado/Rent/Sources/Rent/Domain/RentEntity.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase.swift
  Domado/Rent/Sources/Rent/Presentation/RentView.swift
  Domado/Rent/Sources/Rent/Presentation/RentViewModel.swift
  Domado/Rent/Sources/Rent/Rent.swift
  Domado/Rent/Tests/RentTests/RentTests.swift
Labels: 🧹chore

#38 [chore] Payment 모듈 세팅
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Payment/.gitignore
  Domado/Payment/Package.swift
  Domado/Payment/Sources/Payment/Payment.swift
  Domado/Payment/Tests/PaymentTests/PaymentTests.swift
Labels: 🧹chore

#41 [chore] 결제 모듈 세팅
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Payment/.gitignore
  Domado/Payment/Package.swift
  Domado/Payment/Sources/Payment/Payment.swift
  Domado/Payment/Tests/PaymentTests/PaymentTests.swift
Labels: 🧹chore

#46 [feat] Rent Module Entity 정의
  Domado/Rent/Sources/Rent/Domain/RentEntities/Bike.swift
  Domado/Rent/Sources/Rent/Domain/RentEntities/Common.swift
  Domado/Rent/Sources/Rent/Domain/RentEntities/Handover.swift
  Domado/Rent/Sources/Rent/Domain/RentEntities/QRCode.swift
  Domado/Rent/Sources/Rent/Domain/RentEntities/Rental.swift
  Domado/Rent/Sources/Rent/Domain/RentEntities/Station.swift
  Domado/Rent/Sources/Rent/Domain/RentEntity.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase.swift
Labels: 🐣feature

#45 feat: #42 - Location Entity 작성
  Domado/Location/Sources/Location/Domain/LocationEntities/Bike.swift
  Domado/Location/Sources/Location/Domain/LocationEntities/Hub.swift
  Domado/Location/Sources/Location/Domain/LocationEntities/Location.swift
  Domado/Location/Sources/Location/Domain/LocationEntities/Station.swift
  Domado/Location/Sources/Location/Domain/LocationEntity.swift
Labels: 🐣feature

#51 [fix] Location 패키지 중복된 파일 삭제
  Domado/Location/Sources/Location/Location.swift
Labels: 🐛bug

#52 [enh] 앱 전역 에러 표시 방법 수정
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/AppState/AppDelegateAdapter.swift
  Domado/Domado/Dependency/AppContainer.swift
  Domado/Domado/DomadoApp.swift
  Domado/Domado/Error/AppErrorHandler.swift
  Domado/Domado/Error/AppGlobalErrorHandler.swift
  Domado/Domado/StateStorage/StateStorage.swift
  Domado/Domado/StateStorage/Storage/LocalStorage.swift
  Domado/Domado/StateStorage/Storage/MemoryLocalStorage.swift
  Domado/Domado/View/RootView.swift
Labels: 🔨enhancement

#54 [enh] Router 사용 방식 변경
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/Dependency/AppContainer.swift
  Domado/Domado/View/RootView.swift
  Domado/Domado/View/TempView/LoginView.swift
  Domado/Domado/View/TempView/OnboardingView.swift
  Domado/Domado/View/TempView/QRScannerView.swift
  Domado/Domado/View/TempViewModel/LoginViewModel.swift
  Domado/Domado/View/TempViewModel/OnboardingViewModel.swift
  Domado/Domado/View/TempViewModel/QRScannerViewModel.swift
Labels: 🔨enhancement

#59 [feat] QR 스캔 기능 구현
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Domado/Domado/View/TempView/QRScannerView.swift
  Domado/Domado/View/TempViewModel/QRScannerViewModel.swift
  Domado/Rent/Package.resolved
  Domado/Rent/Package.swift
  Domado/Rent/Sources/Rent/Presentation/RentView.swift
  Domado/Rent/Sources/Rent/Presentation/RentViewModel.swift
Labels: 🐣feature

#56 [feat] Rent Module UseCase 정의
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Handover/Request/CompleteReturnRequest.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Handover/Request/QRScanRequest.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Handover/Request/StartRentalRequest.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Handover/Request/ValidateReturnRequest.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Handover/Response/RentalDetail.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Handover/Response/ValidateReturnResult.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Rental/Request/AcceptHandoverRequest.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Rental/Request/CompleteHandoverRequest.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Rental/Request/CreateHandoverRequest.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Rental/Request/SearchHandoverRequest.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/DTO/Rental/Response/HandoverResult.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/Protocols.swift
Labels: 🐣feature

#62 [feat] QR Scan 손전등 기능
  Domado/Rent/Sources/Rent/Domain/RentUseCase.swift
  Domado/Rent/Sources/Rent/Presentation/RentView.swift
  Domado/Rent/Sources/Rent/Rent.swift
Labels: 🧹chore

#68 [chore] 폰트 적용
  Domado/Core/Sources/Core/UI/CustomFont.swift
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/Info.plist
  Domado/Fonts/NEXON Lv1 Gothic OTF Bold.otf
  Domado/Fonts/Pretendard-Bold.otf
  Domado/Fonts/Pretendard-Medium.otf
  Domado/Fonts/Pretendard-Regular.otf
  Domado/Fonts/Pretendard-SemiBold.otf
Labels: 🧹chore

#73 [feat] User 상태관리 및 화면 Flow 구성
  Domado/Auth/Sources/Auth/Presentation/View/LoginView.swift
  Domado/Auth/Sources/Auth/Presentation/View/SignUpView.swift
  Domado/Auth/Sources/Auth/Presentation/ViewModel/LoginViewModel.swift
  Domado/Auth/Sources/Auth/Presentation/ViewModel/SignUpViewModel.swift
  Domado/Core/Sources/Core/Navigation/NavigationType/FullScreenDestination.swift
  Domado/Core/Sources/Core/Navigation/NavigationType/NavigationDestination.swift
  Domado/Core/Sources/Core/Navigation/NavigationType/SheetDestination.swift
  Domado/Core/Sources/Core/State/AppState.swift
  Domado/Core/Sources/Core/State/StateType/AppUser.swift
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/App/AppContainer.swift
  Domado/Domado/View/RootView.swift
  Domado/Domado/View/TempView/HiBikeGuideView.swift
  Domado/Domado/View/TempView/HomeView.swift
  Domado/Domado/View/TempView/InUseBikeView.swift
  Domado/Domado/View/TempView/ParkingConfirmView.swift
  Domado/Domado/View/TempView/QRScannerView.swift
  Domado/Domado/View/TempView/RentConfirmView.swift
  Domado/Domado/View/TempView/StationDetailView.swift
  Domado/Domado/View/TempView/TempLockView.swift
  Domado/Domado/View/TempView/UnparkingConfirmView.swift
  Domado/Domado/View/TempViewModel/HiBikeGuideViewModel.swift
  Domado/Domado/View/TempViewModel/HomeViewModel.swift
  Domado/Domado/View/TempViewModel/InUseBikeViewModel.swift
  Domado/Domado/View/TempViewModel/ParkingConfirmViewModel.swift
  Domado/Domado/View/TempViewModel/QRScannerViewModel.swift
  Domado/Domado/View/TempViewModel/RentConfirmViewModel.swift
  Domado/Domado/View/TempViewModel/TempLockViewModel.swift
  Domado/Domado/View/TempViewModel/UnparkingConfirmViewModel.swift
Labels: 🐣feature

#75 [feat] WebSocket 방식 네트워킹 구현
  Domado/Auth/Sources/Auth/Presentation/View/AuthView.swift
  Domado/Auth/Sources/Auth/Presentation/ViewModel/AuthViewModel.swift
  Domado/Core/Sources/Core/Logging/LogCategory.swift
  Domado/Core/Sources/Core/Networking/Http/BaseResponse.swift
  Domado/Core/Sources/Core/Networking/Http/CoreNetworkManager.swift
  Domado/Core/Sources/Core/Networking/Http/Endpoint.swift
  Domado/Core/Sources/Core/Networking/Http/HTTPMethod.swift
  Domado/Core/Sources/Core/Networking/Http/NetworkManager.swift
  Domado/Core/Sources/Core/Networking/WebSocket/AnyDecodable.swift
  Domado/Core/Sources/Core/Networking/WebSocket/WebSocketError.swift
  Domado/Core/Sources/Core/Networking/WebSocket/WebSocketManager.swift
  Domado/Core/Sources/Core/Networking/WebSocket/WebSocketMessage.swift
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/App/AppContainer.swift
  Domado/Domado/Assets.xcassets/AppIcon.appiconset/Contents.json
  Domado/Domado/Assets.xcassets/AppIcon.appiconset/HiBike.png
  Domado/Domado/View/RootView.swift
  Domado/Domado/View/TempView/HomeView.swift
  Domado/Domado/View/TempViewModel/HomeViewModel.swift
Labels: 🐣feature

#78 [feat] APNs 서비스 구현
  Domado/Auth/Sources/Auth/Presentation/ViewModel/SignUpViewModel.swift
  Domado/Core/Sources/Core/Logging/LogCategory.swift
  Domado/Core/Sources/Core/Networking/Http/CoreNetworkManager.swift
  Domado/Core/Sources/Core/Notification/DeviceTokenRequest.swift
  Domado/Core/Sources/Core/Notification/PushNotificationManager.swift
  Domado/Core/Sources/Core/State/StateStorage/StateStorage.swift
  Domado/Core/Sources/Core/State/StateStorage/Storage/LocalStorage.swift
  Domado/Core/Sources/Core/State/StateStorage/StorageKey.swift
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/App/AppContainer.swift
  Domado/Domado/App/AppDelegateAdapter.swift
  Domado/Domado/App/DomadoApp.swift
  Domado/Domado/Domado.entitlements
  Domado/Domado/Info.plist
  Domado/Domado/View/RootView.swift
  Domado/Domado/View/TempViewModel/HomeViewModel.swift
Labels: 🐣feature

#77 [Feat] 대여 진행 화면 구현
  Domado/Core/Sources/Core/Navigation/NavigationType/FullScreenDestination.swift
  Domado/Rent/Sources/Rent/Presentation/RentProgressView.swift
  Domado/Rent/Sources/Rent/Presentation/RentProgressViewModel.swift
Labels: 🐣feature

#81 [feat] View 조립하기
  Domado/Core/Sources/Core/UI/Component/Button/BikeInfoCard.swift
  Domado/Core/Sources/Core/UI/Component/Button/HomeInfoCard.swift
  Domado/Core/Sources/Core/UI/Component/Toggle/HibikeToggle.swift
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/App/AppContainer.swift
  Domado/Domado/App/DomadoApp.swift
  Domado/Domado/View/RootView.swift
  Domado/Domado/View/TempView/HomeView.swift
  Domado/Domado/View/TempView/InUseBikeView.swift
  Domado/Domado/View/TempView/ParkingConfirmView.swift
  Domado/Domado/View/TempView/QRScannerView.swift
  Domado/Domado/View/TempView/RentConfirmView.swift
  Domado/Domado/View/TempView/TempLockView.swift
  Domado/Domado/View/TempViewModel/HomeViewModel.swift
  Domado/Domado/View/TempViewModel/InUseBikeViewModel.swift
  Domado/Domado/View/TempViewModel/QRScannerViewModel.swift
  Domado/Domado/View/TempViewModel/RentConfirmViewModel.swift
  Domado/Domado/View/TempViewModel/TempLockViewModel.swift
  Domado/Location/Sources/Location/Domain/LocationManager.swift
  Domado/Rent/Sources/Rent/Data/DTO/Handover/Request/CompleteReturnRequest.swift
  Domado/Rent/Sources/Rent/Data/DTO/Handover/Request/QRScanRequest.swift
  Domado/Rent/Sources/Rent/Data/DTO/Handover/Request/StartRentalRequest.swift
  Domado/Rent/Sources/Rent/Data/DTO/Handover/Request/ValidateReturnRequest.swift
  Domado/Rent/Sources/Rent/Data/DTO/Handover/Response/RentalDetail.swift
  Domado/Rent/Sources/Rent/Data/DTO/Handover/Response/ValidateReturnResult.swift
  Domado/Rent/Sources/Rent/Data/DTO/Rental/Request/AcceptHandoverRequest.swift
  Domado/Rent/Sources/Rent/Data/DTO/Rental/Request/CompleteHandoverRequest.swift
  Domado/Rent/Sources/Rent/Data/DTO/Rental/Request/CreateHandoverRequest.swift
  Domado/Rent/Sources/Rent/Data/DTO/Rental/Request/SearchHandoverRequest.swift
  Domado/Rent/Sources/Rent/Data/DTO/Rental/Response/HandoverResult.swift
  Domado/Rent/Sources/Rent/Domain/RentUseCase/RentUseCase.swift
  Domado/Rent/Sources/Rent/Presentation/RentProgressView.swift
  Domado/Rent/Sources/Rent/Presentation/RentProgressViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/RentViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/View/ActiveRentalView.swift
  Domado/Rent/Sources/Rent/Presentation/View/ParkingConfirmView.swift
  Domado/Rent/Sources/Rent/Presentation/View/RentProgressView.swift
  Domado/Rent/Sources/Rent/Presentation/View/RentView.swift
  Domado/Rent/Sources/Rent/Presentation/View/TempLockView.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/ActiveRentViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/ParkingConfirmViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/RentProgressViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/RentViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/TempLockViewModel.swift
Labels: 🐣feature

#83 [feat] Location Module UI component 추가
  Domado/Core/Sources/Core/Extensions/Color+Extension.swift
  Domado/Core/Sources/Core/Resources/Assets.xcassets/stationBatteryBack.colorset/Contents.json
  Domado/Core/Sources/Core/Resources/Assets.xcassets/stationBatteryGreen.colorset/Contents.json
  Domado/Core/Sources/Core/UI/Components/Button/BikeInfoCard.swift
  Domado/Core/Sources/Core/UI/Components/Button/HomeInfoCard.swift
  Domado/Core/Sources/Core/UI/Components/Button/PrimaryButton.swift
  Domado/Core/Sources/Core/UI/Components/Button/SlideButton.swift
  Domado/Core/Sources/Core/UI/Components/CouponBook.swift
  Domado/Core/Sources/Core/UI/Components/Toggle/HibikeToggle.swift
  Domado/Domado.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Domado/Location/Package.swift
  Domado/Location/Sources/Location/Domain/LocationEntities/Bike.swift
  Domado/Location/Sources/Location/Domain/LocationEntities/Hub.swift
  Domado/Location/Sources/Location/Domain/LocationEntities/Station.swift
  Domado/Location/Sources/Location/Domain/LocationManager.swift
  Domado/Location/Sources/Location/Domain/MapDisplayable.swift
  Domado/Location/Sources/Location/Presentation/Components/Dock.swift
  Domado/Location/Sources/Location/Presentation/Components/HiBikeCard.swift
  Domado/Location/Sources/Location/Presentation/Components/HubCard.swift
  Domado/Location/Sources/Location/Presentation/Components/MyAccountCard.swift
  Domado/Location/Sources/Location/Presentation/Components/RideHistoryCell.swift
  Domado/Location/Sources/Location/Presentation/Components/StationView.swift
  Domado/Location/Sources/Location/Presentation/LocationView.swift
  Domado/Location/Sources/Location/Presentation/MyAccountView.swift
  Domado/Location/Sources/Location/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/bike.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/bike.imageset/bike.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/cash.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/cash.imageset/cash.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/char1.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/char1.imageset/char1.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/char2.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/char2.imageset/char2.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/coupon.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/coupon.imageset/coupon.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/hiBike.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/hiBike.imageset/hiBike.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/hiBikepin.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/hiBikepin.imageset/hiBikepin.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/homepin.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/homepin.imageset/homepin.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/hubpin.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/hubpin.imageset/hubpin.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/mappin.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/mappin.imageset/mappin.png
  Domado/Location/Sources/Location/Resources/Assets.xcassets/myAccount.imageset/Contents.json
  Domado/Location/Sources/Location/Resources/Assets.xcassets/myAccount.imageset/account.png
Labels: 🐣feature

#92 [bug] 앱 종류 후 재실행시 동작하지 않는 현상
  Domado/Core/Sources/Core/Environment/Environment.swift
  Domado/Domado.xcodeproj/project.pbxproj
  Domado/Domado/App/AppContainer.swift
  Domado/Location/Sources/Location/Presentation/View/LocationView.swift
  Domado/Location/Sources/Location/Presentation/ViewModel/LocationViewModel.swift
Labels: 🐛bug

#94 [bug] 마커 선택이 동작하지 않음
  Domado/Domado/Assets.xcassets/posik.imageset/Contents.json
  Domado/Domado/Assets.xcassets/posik.imageset/image 1.png
  Domado/Location/Sources/Location/Presentation/View/LocationView.swift
  Domado/Location/Sources/Location/Presentation/ViewModel/LocationViewModel.swift
Labels: 🐣feature

#98 [feat] 결제 요청시 로딩 인디케이터 표시
  Domado/Core/Sources/Core/State/AppState.swift
  Domado/Domado/App/AppContainer.swift
  Domado/Rent/Sources/Rent/Presentation/View/ActiveRentalView.swift
  Domado/Rent/Sources/Rent/Presentation/View/TempLockView.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/ActiveRentViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/HiBikeCompleteViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/ReturnBikeViewModel.swift
  Domado/Rent/Sources/Rent/Presentation/ViewModel/TempLockViewModel.swift
Labels: 🐣feature
